{
 "title": "trassir",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Текущая глубина архива основного потока",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "disks_stat_main_days", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "uptime", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Диски",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "disks{job=\"trassir-metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "БД",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "database", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Загрузка ЦПУ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 7 },
   "targets": [
    { "expr": "cpu_load", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ошибки в скриптах",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "automation", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Сетевые ошибки",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "network", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Всего камер",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "channels_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Камер без ошибок",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "channels_online", "legendFormat": "__auto" }
   ]
  }
 ]
}